In [1]:
import pandas as pd
import numpy as np


df = pd.read_csv('~/Downloads/Auto.csv')
df = df[df['horsepower'] != '?']
df['horsepower'] = df['horsepower'].astype(float)
df['muscle'] = df['horsepower'].apply(lambda x: 0 if x < np.mean(df['horsepower']) else 1)

train_len = int(len(df) * 0.8)
train = df.iloc[:train_len]
test = df.iloc[train_len:]

In [3]:
from sklearn.linear_model import LinearRegression


model = LinearRegression()
model.fit(train[['horsepower', 'cylinders', 'weight']], train['mpg'])
model.coef_

array([-0.02458819, -0.28837181, -0.00511879])

In [12]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train[['year', 'cylinders', 'weight']] = scaler.fit_transform(train[['year', 'cylinders', 'weight']])


model = Ridge(1)
model.fit(train[['year', 'cylinders', 'weight']], train['mpg'])
model.coef_

/var/folders/ps/g7dr3f8x0vnbdn4gn57pntfh0000gn/T/ipykernel_69045/1339598524.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[['year', 'cylinders', 'weight']] = scaler.fit_transform(train[['year', 'cylinders', 'weight']])


array([ 1.64348105, -0.58670464, -5.00691343])

In [19]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train[['year', 'cylinders', 'weight']] = scaler.fit_transform(train[['year', 'cylinders', 'weight']])


model = Lasso(alpha=10)
model.fit(train[['year', 'cylinders', 'weight']], train['mpg'])
model.coef_

/var/folders/ps/g7dr3f8x0vnbdn4gn57pntfh0000gn/T/ipykernel_69045/2417004599.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train[['year', 'cylinders', 'weight']] = scaler.fit_transform(train[['year', 'cylinders', 'weight']])


array([ 0., -0., -0.])